name = "GialusConfig"
uuid = "79c46ed4-41ca-49c8-8587-7d8abe00f603"
authors = ["Gianluca Fuwa"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
